Add ability to stretch the PullRequestStatsCard vertically in the grid
RoadieHQ/backstage-plugin-github-pull-requests pull request #86
Opened 2021-04-13 16:39 UTC by bobalong79

The optional `vstretch` attribute when applied to the card will stretch it vertically to fill all available space.

E.g.

```ts
<Grid item xs={8}>
  <JenkinsLatestRunCard branch="main" />
</Grid>
<Grid item xs={4}>
  <PullRequestsStatsCard vstretch={true} />
</Grid>
```

Before:
![image](https://user-images.githubusercontent.com/14176917/114588860-0c88be80-9c7f-11eb-8e64-21925d8f0cce.png)

After:
![image](https://user-images.githubusercontent.com/14176917/114588795-f7ac2b00-9c7e-11eb-989f-481b71c75052.png)

2021-04-13 21:50 UTC, bobalong79 commented
Hey, I've seen a much better way of doing this, same as the SonarQube plugin - using the InfoCard variants, which includes a "fullHeight" one that should do what I need. I will change this tomorrow to support the variants instead.

2021-04-14 09:37 UTC, bobalong79 commented
I've updated the code for variant support and amended the description and title of the PR

2021-04-14 10:02 UTC, dtuite approved these changes

2021-04-14 10:03 UTC, dtuite requested changes
@bobalong79 Looks good, thanks. 

Could you add a patch version bump please? That way a new version will be automatically released when we merge this to `main`.

2021-04-14 10:30 UTC, bobalong79 commented
Great 👍 I've added the patch increment.

2021-04-14 11:32 UTC, dtuite approved these changes

2021-04-14 11:32 UTC, merged